# Generated by Django 3.1.1 on 2021-05-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
